version: '3'
services:
  node-app:
    container_name: node-app
    restart: always
    build: .
    ports:
      - '4000:4000'
    depends_on:
      - redis-server
  redis-server:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
